# Generated by Django 4.1.3 on 2023-10-18 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("pagos", "0001_initial"),
        ("cart", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="pagos",
            name="Compador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Pagos_Comprador",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ordenes",
            name="Cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ordenes_comprador",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ordenes",
            name="ItemsComprados",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productos_comprados",
                to="cart.cartitems",
            ),
        ),
        migrations.AddField(
            model_name="ordenes",
            name="MetodoPago",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="metodo_pago_ordenes",
                to="pagos.pagos",
            ),
        ),
        migrations.AddConstraint(
            model_name="ordenes",
            constraint=models.UniqueConstraint(
                fields=("ItemsComprados",), name="unique_item_comprados"
            ),
        ),
        migrations.AddConstraint(
            model_name="ordenes",
            constraint=models.UniqueConstraint(
                fields=("MetodoPago",), name="unique_metodo_pago"
            ),
        ),
    ]
