# Generated by Django 4.1.3 on 2023-10-14 19:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "ProductID",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ProductID"
                    ),
                ),
                (
                    "Nombre",
                    models.CharField(max_length=60, verbose_name="Nombre del producto"),
                ),
                (
                    "Cantidad",
                    models.SmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Cantidad de producto",
                    ),
                ),
                (
                    "Tipo",
                    models.CharField(
                        choices=[("A", "X"), ("B", "Z"), ("C", "Y")],
                        max_length=20,
                        verbose_name="Tipo de producto",
                    ),
                ),
                (
                    "Marca",
                    models.CharField(max_length=60, verbose_name="Marca del producto"),
                ),
                ("Precio", models.IntegerField(verbose_name="Precio")),
                (
                    "Creado_el",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creacion"
                    ),
                ),
                (
                    "Modificado_el",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Modificacion"
                    ),
                ),
            ],
        ),
    ]
