# Generated by Django 4.1.3 on 2023-10-17 20:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CodigosProductos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ProductoCodigo",
                    models.CharField(
                        choices=[("A", "X"), ("B", "Z"), ("C", "Y")],
                        max_length=40,
                        unique=True,
                        verbose_name="Codigo de Producto",
                    ),
                ),
                (
                    "TipoProducto",
                    models.CharField(
                        choices=[("A", "X"), ("B", "Z"), ("C", "Y")],
                        max_length=40,
                        unique=True,
                        verbose_name="Tipo de Producto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "ProductID",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ProductID"
                    ),
                ),
                (
                    "Nombre",
                    models.CharField(max_length=60, verbose_name="Nombre del producto"),
                ),
                (
                    "Cantidad",
                    models.SmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Cantidad de producto",
                    ),
                ),
                (
                    "Marca",
                    models.CharField(max_length=60, verbose_name="Marca del producto"),
                ),
                ("Precio", models.IntegerField(verbose_name="Precio")),
                (
                    "Creado_el",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creacion"
                    ),
                ),
                (
                    "Modificado_el",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Modificacion"
                    ),
                ),
                (
                    "Codigos",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ProductCodigo",
                        to="Core.codigosproductos",
                        to_field="ProductoCodigo",
                    ),
                ),
            ],
        ),
    ]
