# Generated by Django 4.1.3 on 2023-10-18 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="Creado_por",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="Tipo",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ProductTipo",
                to="Core.tipoproductos",
                to_field="TipoProducto",
            ),
        ),
    ]
