# Generated by Django 4.2.6 on 2023-11-05 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cart", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitems",
            name="fechaAgregado",
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name="carrito",
            name="UserCart",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="CarritoDeUser",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
