# Generated by Django 4.2.6 on 2023-11-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0003_cartitems_fechaagregado_alter_carrito_usercart"),
    ]

    operations = [
        migrations.AddField(
            model_name="carrito",
            name="Completado",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="carrito",
            name="Fecha_Creado",
            field=models.DateTimeField(null=True),
        ),
    ]
