# Generated by Django 4.2.6 on 2023-11-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0004_carrito_completado_carrito_fecha_creado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carrito",
            name="Fecha_Creado",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
